test: add fetcher unit tests (IDs 27, 28, 33, 34)
Add tests for parse_page, _extract_abstract, _extract_published_version,
_normalize_date, and _parse_search_result.

Also fix a bug in _parse_search_result where authors=None caused
TypeError: 'NoneType' object is not iterable.